version: "3.3"

services:
    mongodb:
        image : mongo
        environment:
            MONGO_INITDB_ROOT_USERNAME: mongodb
            MONGO_INITDB_ROOT_PASSWORD: mongodb
        ports:
            - 27017:27017
        volumes:
            - ./data/db/:/data/db/
        expose:
            - 27017
        restart: unless-stopped
    api:
        build: ./api
        command: python main.py
        environment:
            MONGO_URL: mongodb://mongodb:mongodb@mongodb:27017/
        ports:
            - "8000:8000"
        volumes:
            - ./api:/code
        depends_on:
            - mongodb
    scraping:
        build: ./scraper
        command: python scrap.py
        volumes:
            - ./scraper:/code
        depends_on:
            - mongodb
